version: "3.8"

services:
    php:
        build:
          dockerfile: ./.infrastructure/docker/php/Dockerfile
          context: .
        volumes:
            - .:/var/www/html:cached
        env_file: .env

    postgresql:
        image: postgres:15-alpine3.17
        volumes:
            - postgresql_volume:/var/lib/postgresql/data
        env_file: .env
        ports:
          - 5432:5432

    redis:
      image: redis:7.0
      env_file: .env
      ports:
        - "6379:6379"

volumes:
    postgresql_volume:
